# Generated by Django 3.2.9 on 2021-11-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1)),
                ('adress', models.CharField(max_length=30)),
                ('admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
                ('status', models.CharField(default='OK', max_length=10)),
                ('dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources_2054.department')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_type', models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop')], max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=30)),
                ('status', models.CharField(default='OK', max_length=10)),
                ('dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources_2054.department')),
            ],
        ),
    ]
